# Generated by Django 3.0.7 on 2020-08-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optional',
            name='internship',
        ),
        migrations.DeleteModel(
            name='Compulsary',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Optional',
        ),
    ]
